name: CI-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mysql-setup:
    runs-on: ubuntu-latest
    container: python:3.13.0-alpine
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 3
        ports:
          - 3306:3306
          
    steps:
      - name: MySQL Setup Complete
        run: echo "MySQL setup job complete."

  migrate-and-test:
    runs-on: ubuntu-latest
    container: python:3.13.0-alpine
    needs: mysql-setup   

    env:
      DB_NAME: test_db
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: 127.0.0.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install MySQL dependencies
        run: |
          apk update
          apk add --no-cache mariadb-client mariadb-dev build-base libffi-dev python3-dev

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to Be Ready
        run: |
          until mysqladmin ping -h "$DB_HOST" --silent; do
            echo 'Waiting for MySQL...'
            sleep 2
          done
          
      - name: Run Migrations and Tests
        working-directory: ./littlelemon
        run: |
          python manage.py migrate
          python manage.py test
