name: CI-pipeline

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3.13.0-alpine

        services:
            mysql:
              image: mysql:latest
              env:
                MYSQL_ROOT_PASSWORD: password
                DB_PASSWORD: password
                DB_NAME: test_db
                DB_USER: user
              options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 3
              ports:
                - 3306:3306

        env:
          DB_NAME: test_db
          DB_USER: user
          DB_PASSWORD: password
          DB_HOST: mysql
                
            
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install MySQL dependencies
              run: |
                apk update
                apk add --no-cache mariadb-dev build-base libffi-dev python3-dev

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Wait for MySQL to be ready
              run: |
                  echo "Waiting for MySQL container to be healthy..."
                  until [ "$(docker inspect --format='{{.State.Health.Status}}' mysql)" = "healthy" ]; do
                    echo "MySQL is not ready yet. Waiting..."
                    sleep 2
                  done
                  echo "MySQL is ready!"

            - name: Run Migration and Tests
              working-directory: ./littlelemon
              run: |
                python manage.py migrate
                python manage.py test
              env:
                DB_NAME: test_db
                DB_USER: user
                DB_PASSWORD: password
                DB_HOST: mysql
                #DATABASE_URL: mysql://user:password@127.0.0.1:3306/test_db
            
